default_stages: [pre-commit]
exclude: (\.min\.js$|\.svg$|\.m$)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: e05c5c0818279e5ac248ac9e954431ba58865e61 # frozen: v0.15.7
    hooks:
      - id: ruff-check
  - repo: https://github.com/hoxbro/clean_notebook
    rev: v0.1.15a2
    hooks:
      - id: clean-notebook
